name: Render Ghidra Graph
on:
  workflow_dispatch:
    inputs:
      graphPath:
        description: Path or URL to the graph
        required: true
        type: string


jobs:
  post:
    name: "Render"
    runs-on: "ubuntu-latest"
    steps:
      # Clone and install the Python project
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync

      # Clone and install the typescript scripts
      - uses: actions/checkout@v4
        with:
          repository: "tmr232/function-graph-overview"
          ref: "bc395101f52087c0235d210ad3dd0806fd1f9a4e"
          path: "function-graph-overview"

      # Fetch the Ghidra export indices
      - uses: actions/checkout@v4
        with:
          repository: "v-p-b/ghidra-function-graph-datasets"
          ref: "main"
          path: "ghidra-indices"

      - uses: oven-sh/setup-bun@v2
        with:
          # Specific version is needed because of breaking changes in Bun 1.1.45
          # See https://github.com/tmr232/function-graph-overview/issues/76 for details.
          bun-version: "1.1.44"
      - run: |
          cd function-graph-overview
          bun install

      # Render Dark
      - run: bun run function-graph-overview/scripts/render-graph.ts ${{ inputs.graphPath }} > dark.svg

      # Render Light
      - run: bun run function-graph-overview/scripts/render-graph.ts --colors light ${{ inputs.graphPath }} > light.svg



      # Upload result
      - uses: actions/upload-artifact@v4
        with:
          name: SVG Output
          path: "*.svg"


